using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PV_NinBAnim : MonoBehaviour
{

    private Animator animator;
    public Transform NinjaB1;//ï¿½Ú“Iï¿½nï¿½Æ‚È‚ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìƒgï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½tï¿½Hï¿½[ï¿½ï¿½ï¿½iï¿½[ï¿½p
    public Transform NinjaB2;//ï¿½Ú“Iï¿½nï¿½Æ‚È‚ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìƒgï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½tï¿½Hï¿½[ï¿½ï¿½ï¿½iï¿½[ï¿½p
    public Transform NinjaB3;//ï¿½Ú“Iï¿½nï¿½Æ‚È‚ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìƒgï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½tï¿½Hï¿½[ï¿½ï¿½ï¿½iï¿½[ï¿½p
    private UnityEngine.AI.NavMeshAgent agent;     //ï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½gï¿½Æ‚È‚ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½NavMeshAgentï¿½iï¿½[ï¿½p 
    public GameObject NinBSayBox;
    private string[] NinBsay = new string[2];
    public Text NinBtextBox;
    private int i;
    bool fa = true;
    public Image Title;
    public Image Titleback;
    float red1, green1, blue1, alfa1;   //ï¿½pï¿½lï¿½ï¿½ï¿½ÌFï¿½Aï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½Ç—ï¿½
    float red2, green2, blue2, alfa2;   //ï¿½pï¿½lï¿½ï¿½ï¿½ÌFï¿½Aï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½Ç—ï¿½
    bool isFadeIn1 = false;
    bool isFadeIn2 = false;

    //public Camera pvCam;
    //float maxFOV = 60;
    //float minFOV = 35;

    // Start is called before the first frame update
    void Start()
    {
        animator = GetComponent<Animator>();
        //ï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½gï¿½ï¿½NaveMeshAgentï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
        agent = GetComponent<UnityEngine.AI.NavMeshAgent>();
        Invoke("PVstar", 10.0f);
        animator.SetBool("Go", true);
        animator.SetBool("pvFall", false);
        NinBsay[0] = " ãŠ ã‹ ã— ã‚‰ ï¼ \n å•† ã„ ãŠ ã¤ ã‹ ã‚Œ ã• ã¾ ï¼ ";
        NinBsay[1] = " ã‚ ã£ ï¼ \n å¾… ã£ ã¦ ã ã  ã• ã„ ã‚ˆ ï½ ";


        red1 = Title.color.r;
        green1 = Title.color.g;
        blue1 = Title.color.b;
        alfa1 = 0;


        red2 = Titleback.color.r;
        green2 = Titleback.color.g;
        blue2 = Titleback.color.b;
        alfa2 = 0;

    
    }

    void PVstar()
    {
        //ï¿½Ú“Iï¿½nï¿½Æ‚È‚ï¿½ï¿½ï¿½Wï¿½ï¿½İ’è‚·ï¿½ï¿½
        agent.destination = NinjaB1.position;
    }


    // Update is called once per frame
    void Update()
    {
        if(isFadeIn1)
        {
            StartTitle();
        }

        if(isFadeIn2)
        {
            StartTitleBack();
        }
    }
    //ï¿½ï¿½Êï¿½ï¿½ï¿½
    IEnumerator NinBanim()
    {

        yield return new WaitForSeconds(1.0f);
        animator.SetBool("pvStay", true);
        yield return new WaitForSeconds(0.5f);
        NinBSayBox.gameObject.SetActive(true);
        NinBtextBox.text = "";
        yield return new WaitForSeconds(0.1f);
        StartCoroutine(ChangeSay());
        i++;
        yield return new WaitForSeconds(2.0f);
        StartCoroutine(ChangeSay());
        yield return new WaitForSeconds(2.0f);
        agent.destination = NinjaB2.position;
        NinBSayBox.gameObject.SetActive(false);
        animator.SetBool("Go", true);
        animator.SetBool("pvStay", false);

        yield return new WaitForSeconds(4.5f);
        animator.SetBool("Go", true);
        animator.SetBool("pvFall", false);
        agent.destination = NinjaB3.position;
        yield return new WaitForSeconds(2.0f);
        isFadeIn1 = true;
        isFadeIn2 = true;
    }

    //ï¿½eï¿½Lï¿½Xï¿½gï¿½ï¿½ï¿½ï¿½Ö‚ï¿½
    IEnumerator ChangeSay()
    {
        NinBtextBox.text = "";

        string[] words;
        // ï¿½ï¿½ï¿½pï¿½Xï¿½yï¿½[ï¿½Xï¿½Å•ï¿½ï¿½ï¿½ï¿½ğ•ªŠï¿½ï¿½ï¿½ï¿½ï¿½B
        words = NinBsay[i].Split(' ');

        foreach (var word in words)
        {

            // 0.1ï¿½bï¿½ï¿½ï¿½İ‚Å‚Pï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â•\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B
            NinBtextBox.text = NinBtextBox.text + word;
            yield return new WaitForSeconds(0.08f);

        }
        PV_AnimFine.FineWalk = true;
        
    }

    void OnTriggerEnter(Collider other)
    {

        if (other.CompareTag("GoalA"))
        {
            if (fa)
            {
                StartCoroutine(NinBanim());
                fa = false;
            }
        }

        if (other.CompareTag("GoalB"))
        {
            animator.SetBool("Go", false);
            animator.SetBool("pvFall", true);

        }
    }

    void StartTitle()
    {
        alfa1 += 0.25f * Time.deltaTime;                //a)ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½
        SetAlpha1();                      //b)ï¿½ÏXï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½pï¿½lï¿½ï¿½ï¿½É”ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½
        if (alfa1 >= 0.84)
        {                    //c)ï¿½ï¿½ï¿½Sï¿½É“ï¿½ï¿½ï¿½ï¿½É‚È‚ï¿½ï¿½ï¿½ï¿½çˆï¿½ï¿½ï¿½ğ”²‚ï¿½ï¿½ï¿½
            isFadeIn1 = false ;
        }
    }

    void StartTitleBack()
    {
        alfa2 += 0.3f * Time.deltaTime;                //a)ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½
        SetAlpha2();                      //b)ï¿½ÏXï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½pï¿½lï¿½ï¿½ï¿½É”ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½
        if (alfa2 >= 1)
        {                    //c)ï¿½ï¿½ï¿½Sï¿½É“ï¿½ï¿½ï¿½ï¿½É‚È‚ï¿½ï¿½ï¿½ï¿½çˆï¿½ï¿½ï¿½ğ”²‚ï¿½ï¿½ï¿½
            isFadeIn2 = false;
        }
    }

    void SetAlpha1()
    {
        Title.color = new Color(red1, green1, blue1, alfa1);
    }

    void SetAlpha2()
    {
        Titleback.color = new Color(red2, green2, blue2, alfa2);
    }

}
